<?php
/**
 * Candidate
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EvoliaApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace EvoliaV3\Model;

use \ArrayAccess;
use \EvoliaV3\ObjectSerializer;

/**
 * Candidate Class Doc Comment
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Candidate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Candidate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'titre' => 'int',
'nom' => 'string',
'pre_nom' => 'string',
'id_ref' => 'string',
'qualification' => 'string',
'nationalite' => 'string',
'nom_jf' => 'string',
'date_naissance' => '\DateTime',
'telephone_portable' => 'string',
'email' => 'string',
'nom_voie' => 'string',
'cp' => 'string',
'commune' => 'string',
'numsecu' => 'string',
'numsecu_cle' => 'string',
'lieu_naiss' => 'string',
'pays_naiss' => 'string',
'pays' => 'string',
'liste_agences' => 'string[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'titre' => 'int32',
'nom' => null,
'pre_nom' => null,
'id_ref' => null,
'qualification' => null,
'nationalite' => null,
'nom_jf' => null,
'date_naissance' => 'date-time',
'telephone_portable' => null,
'email' => null,
'nom_voie' => null,
'cp' => null,
'commune' => null,
'numsecu' => null,
'numsecu_cle' => null,
'lieu_naiss' => null,
'pays_naiss' => null,
'pays' => null,
'liste_agences' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'titre' => 'titre',
'nom' => 'nom',
'pre_nom' => 'preNom',
'id_ref' => 'idRef',
'qualification' => 'qualification',
'nationalite' => 'nationalite',
'nom_jf' => 'nomJF',
'date_naissance' => 'dateNaissance',
'telephone_portable' => 'telephonePortable',
'email' => 'email',
'nom_voie' => 'nomVoie',
'cp' => 'cp',
'commune' => 'commune',
'numsecu' => 'numsecu',
'numsecu_cle' => 'numsecuCle',
'lieu_naiss' => 'lieu_Naiss',
'pays_naiss' => 'paysNaiss',
'pays' => 'pays',
'liste_agences' => 'listeAgences'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'titre' => 'setTitre',
'nom' => 'setNom',
'pre_nom' => 'setPreNom',
'id_ref' => 'setIdRef',
'qualification' => 'setQualification',
'nationalite' => 'setNationalite',
'nom_jf' => 'setNomJf',
'date_naissance' => 'setDateNaissance',
'telephone_portable' => 'setTelephonePortable',
'email' => 'setEmail',
'nom_voie' => 'setNomVoie',
'cp' => 'setCp',
'commune' => 'setCommune',
'numsecu' => 'setNumsecu',
'numsecu_cle' => 'setNumsecuCle',
'lieu_naiss' => 'setLieuNaiss',
'pays_naiss' => 'setPaysNaiss',
'pays' => 'setPays',
'liste_agences' => 'setListeAgences'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'titre' => 'getTitre',
'nom' => 'getNom',
'pre_nom' => 'getPreNom',
'id_ref' => 'getIdRef',
'qualification' => 'getQualification',
'nationalite' => 'getNationalite',
'nom_jf' => 'getNomJf',
'date_naissance' => 'getDateNaissance',
'telephone_portable' => 'getTelephonePortable',
'email' => 'getEmail',
'nom_voie' => 'getNomVoie',
'cp' => 'getCp',
'commune' => 'getCommune',
'numsecu' => 'getNumsecu',
'numsecu_cle' => 'getNumsecuCle',
'lieu_naiss' => 'getLieuNaiss',
'pays_naiss' => 'getPaysNaiss',
'pays' => 'getPays',
'liste_agences' => 'getListeAgences'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['titre'] = isset($data['titre']) ? $data['titre'] : null;
        $this->container['nom'] = isset($data['nom']) ? $data['nom'] : null;
        $this->container['pre_nom'] = isset($data['pre_nom']) ? $data['pre_nom'] : null;
        $this->container['id_ref'] = isset($data['id_ref']) ? $data['id_ref'] : null;
        $this->container['qualification'] = isset($data['qualification']) ? $data['qualification'] : null;
        $this->container['nationalite'] = isset($data['nationalite']) ? $data['nationalite'] : null;
        $this->container['nom_jf'] = isset($data['nom_jf']) ? $data['nom_jf'] : null;
        $this->container['date_naissance'] = isset($data['date_naissance']) ? $data['date_naissance'] : null;
        $this->container['telephone_portable'] = isset($data['telephone_portable']) ? $data['telephone_portable'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['nom_voie'] = isset($data['nom_voie']) ? $data['nom_voie'] : null;
        $this->container['cp'] = isset($data['cp']) ? $data['cp'] : null;
        $this->container['commune'] = isset($data['commune']) ? $data['commune'] : null;
        $this->container['numsecu'] = isset($data['numsecu']) ? $data['numsecu'] : null;
        $this->container['numsecu_cle'] = isset($data['numsecu_cle']) ? $data['numsecu_cle'] : null;
        $this->container['lieu_naiss'] = isset($data['lieu_naiss']) ? $data['lieu_naiss'] : null;
        $this->container['pays_naiss'] = isset($data['pays_naiss']) ? $data['pays_naiss'] : null;
        $this->container['pays'] = isset($data['pays']) ? $data['pays'] : null;
        $this->container['liste_agences'] = isset($data['liste_agences']) ? $data['liste_agences'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets titre
     *
     * @return int
     */
    public function getTitre()
    {
        return $this->container['titre'];
    }

    /**
     * Sets titre
     *
     * @param int $titre titre
     *
     * @return $this
     */
    public function setTitre($titre)
    {
        $this->container['titre'] = $titre;

        return $this;
    }

    /**
     * Gets nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->container['nom'];
    }

    /**
     * Sets nom
     *
     * @param string $nom nom
     *
     * @return $this
     */
    public function setNom($nom)
    {
        $this->container['nom'] = $nom;

        return $this;
    }

    /**
     * Gets pre_nom
     *
     * @return string
     */
    public function getPreNom()
    {
        return $this->container['pre_nom'];
    }

    /**
     * Sets pre_nom
     *
     * @param string $pre_nom pre_nom
     *
     * @return $this
     */
    public function setPreNom($pre_nom)
    {
        $this->container['pre_nom'] = $pre_nom;

        return $this;
    }

    /**
     * Gets id_ref
     *
     * @return string
     */
    public function getIdRef()
    {
        return $this->container['id_ref'];
    }

    /**
     * Sets id_ref
     *
     * @param string $id_ref id_ref
     *
     * @return $this
     */
    public function setIdRef($id_ref)
    {
        $this->container['id_ref'] = $id_ref;

        return $this;
    }

    /**
     * Gets qualification
     *
     * @return string
     */
    public function getQualification()
    {
        return $this->container['qualification'];
    }

    /**
     * Sets qualification
     *
     * @param string $qualification qualification
     *
     * @return $this
     */
    public function setQualification($qualification)
    {
        $this->container['qualification'] = $qualification;

        return $this;
    }

    /**
     * Gets nationalite
     *
     * @return string
     */
    public function getNationalite()
    {
        return $this->container['nationalite'];
    }

    /**
     * Sets nationalite
     *
     * @param string $nationalite nationalite
     *
     * @return $this
     */
    public function setNationalite($nationalite)
    {
        $this->container['nationalite'] = $nationalite;

        return $this;
    }

    /**
     * Gets nom_jf
     *
     * @return string
     */
    public function getNomJf()
    {
        return $this->container['nom_jf'];
    }

    /**
     * Sets nom_jf
     *
     * @param string $nom_jf nom_jf
     *
     * @return $this
     */
    public function setNomJf($nom_jf)
    {
        $this->container['nom_jf'] = $nom_jf;

        return $this;
    }

    /**
     * Gets date_naissance
     *
     * @return \DateTime
     */
    public function getDateNaissance()
    {
        return $this->container['date_naissance'];
    }

    /**
     * Sets date_naissance
     *
     * @param \DateTime $date_naissance date_naissance
     *
     * @return $this
     */
    public function setDateNaissance($date_naissance)
    {
        $this->container['date_naissance'] = $date_naissance;

        return $this;
    }

    /**
     * Gets telephone_portable
     *
     * @return string
     */
    public function getTelephonePortable()
    {
        return $this->container['telephone_portable'];
    }

    /**
     * Sets telephone_portable
     *
     * @param string $telephone_portable telephone_portable
     *
     * @return $this
     */
    public function setTelephonePortable($telephone_portable)
    {
        $this->container['telephone_portable'] = $telephone_portable;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets nom_voie
     *
     * @return string
     */
    public function getNomVoie()
    {
        return $this->container['nom_voie'];
    }

    /**
     * Sets nom_voie
     *
     * @param string $nom_voie nom_voie
     *
     * @return $this
     */
    public function setNomVoie($nom_voie)
    {
        $this->container['nom_voie'] = $nom_voie;

        return $this;
    }

    /**
     * Gets cp
     *
     * @return string
     */
    public function getCp()
    {
        return $this->container['cp'];
    }

    /**
     * Sets cp
     *
     * @param string $cp cp
     *
     * @return $this
     */
    public function setCp($cp)
    {
        $this->container['cp'] = $cp;

        return $this;
    }

    /**
     * Gets commune
     *
     * @return string
     */
    public function getCommune()
    {
        return $this->container['commune'];
    }

    /**
     * Sets commune
     *
     * @param string $commune commune
     *
     * @return $this
     */
    public function setCommune($commune)
    {
        $this->container['commune'] = $commune;

        return $this;
    }

    /**
     * Gets numsecu
     *
     * @return string
     */
    public function getNumsecu()
    {
        return $this->container['numsecu'];
    }

    /**
     * Sets numsecu
     *
     * @param string $numsecu numsecu
     *
     * @return $this
     */
    public function setNumsecu($numsecu)
    {
        $this->container['numsecu'] = $numsecu;

        return $this;
    }

    /**
     * Gets numsecu_cle
     *
     * @return string
     */
    public function getNumsecuCle()
    {
        return $this->container['numsecu_cle'];
    }

    /**
     * Sets numsecu_cle
     *
     * @param string $numsecu_cle numsecu_cle
     *
     * @return $this
     */
    public function setNumsecuCle($numsecu_cle)
    {
        $this->container['numsecu_cle'] = $numsecu_cle;

        return $this;
    }

    /**
     * Gets lieu_naiss
     *
     * @return string
     */
    public function getLieuNaiss()
    {
        return $this->container['lieu_naiss'];
    }

    /**
     * Sets lieu_naiss
     *
     * @param string $lieu_naiss lieu_naiss
     *
     * @return $this
     */
    public function setLieuNaiss($lieu_naiss)
    {
        $this->container['lieu_naiss'] = $lieu_naiss;

        return $this;
    }

    /**
     * Gets pays_naiss
     *
     * @return string
     */
    public function getPaysNaiss()
    {
        return $this->container['pays_naiss'];
    }

    /**
     * Sets pays_naiss
     *
     * @param string $pays_naiss pays_naiss
     *
     * @return $this
     */
    public function setPaysNaiss($pays_naiss)
    {
        $this->container['pays_naiss'] = $pays_naiss;

        return $this;
    }

    /**
     * Gets pays
     *
     * @return string
     */
    public function getPays()
    {
        return $this->container['pays'];
    }

    /**
     * Sets pays
     *
     * @param string $pays pays
     *
     * @return $this
     */
    public function setPays($pays)
    {
        $this->container['pays'] = $pays;

        return $this;
    }

    /**
     * Gets liste_agences
     *
     * @return string[]
     */
    public function getListeAgences()
    {
        return $this->container['liste_agences'];
    }

    /**
     * Sets liste_agences
     *
     * @param string[] $liste_agences liste_agences
     *
     * @return $this
     */
    public function setListeAgences($liste_agences)
    {
        $this->container['liste_agences'] = $liste_agences;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
