<?php
/**
 * Candidate
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EvoliaApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace EvoliaV3\Model;

use \ArrayAccess;
use \EvoliaV3\ObjectSerializer;

/**
 * Candidate Class Doc Comment
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Candidate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Candidate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'titre' => 'int',
'nom' => 'string',
'prenom' => 'string',
'id_ref' => 'string',
'nom_jf' => 'string',
'qualification' => 'string',
'nationalite' => 'string',
'date_naissance' => '\DateTime',
'telephone_portable' => 'string',
'telephone_domicile' => 'string',
'qualif' => 'string',
'bq_iban' => 'string',
'bq_bic' => 'string',
'bq_titulaire' => 'string',
'bq_domiciliation' => 'string',
'email' => 'string',
'nom_voie' => 'string',
'num_voie' => 'string',
'comp_voie' => 'string',
'bis_voie' => 'string',
'cp' => 'string',
'insee_commune' => 'string',
'commune' => 'string',
'num_secu' => 'string',
'num_secu_cle' => 'string',
'lieu_naiss' => 'string',
'pays_naiss' => 'string',
'pays' => 'string',
'liste_agences' => 'string[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'titre' => 'int32',
'nom' => null,
'prenom' => null,
'id_ref' => null,
'nom_jf' => null,
'qualification' => null,
'nationalite' => null,
'date_naissance' => 'date-time',
'telephone_portable' => null,
'telephone_domicile' => null,
'qualif' => null,
'bq_iban' => null,
'bq_bic' => null,
'bq_titulaire' => null,
'bq_domiciliation' => null,
'email' => null,
'nom_voie' => null,
'num_voie' => null,
'comp_voie' => null,
'bis_voie' => null,
'cp' => null,
'insee_commune' => null,
'commune' => null,
'num_secu' => null,
'num_secu_cle' => null,
'lieu_naiss' => null,
'pays_naiss' => null,
'pays' => null,
'liste_agences' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'titre' => 'titre',
'nom' => 'nom',
'prenom' => 'prenom',
'id_ref' => 'idRef',
'nom_jf' => 'nomJF',
'qualification' => 'qualification',
'nationalite' => 'nationalite',
'date_naissance' => 'dateNaissance',
'telephone_portable' => 'telephonePortable',
'telephone_domicile' => 'telephoneDomicile',
'qualif' => 'qualif',
'bq_iban' => 'bqIban',
'bq_bic' => 'bqBic',
'bq_titulaire' => 'bqTitulaire',
'bq_domiciliation' => 'bqDomiciliation',
'email' => 'email',
'nom_voie' => 'nomVoie',
'num_voie' => 'numVoie',
'comp_voie' => 'compVoie',
'bis_voie' => 'bisVoie',
'cp' => 'cp',
'insee_commune' => 'inseeCommune',
'commune' => 'commune',
'num_secu' => 'numSecu',
'num_secu_cle' => 'numSecuCle',
'lieu_naiss' => 'lieuNaiss',
'pays_naiss' => 'paysNaiss',
'pays' => 'pays',
'liste_agences' => 'listeAgences'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'titre' => 'setTitre',
'nom' => 'setNom',
'prenom' => 'setPrenom',
'id_ref' => 'setIdRef',
'nom_jf' => 'setNomJf',
'qualification' => 'setQualification',
'nationalite' => 'setNationalite',
'date_naissance' => 'setDateNaissance',
'telephone_portable' => 'setTelephonePortable',
'telephone_domicile' => 'setTelephoneDomicile',
'qualif' => 'setQualif',
'bq_iban' => 'setBqIban',
'bq_bic' => 'setBqBic',
'bq_titulaire' => 'setBqTitulaire',
'bq_domiciliation' => 'setBqDomiciliation',
'email' => 'setEmail',
'nom_voie' => 'setNomVoie',
'num_voie' => 'setNumVoie',
'comp_voie' => 'setCompVoie',
'bis_voie' => 'setBisVoie',
'cp' => 'setCp',
'insee_commune' => 'setInseeCommune',
'commune' => 'setCommune',
'num_secu' => 'setNumSecu',
'num_secu_cle' => 'setNumSecuCle',
'lieu_naiss' => 'setLieuNaiss',
'pays_naiss' => 'setPaysNaiss',
'pays' => 'setPays',
'liste_agences' => 'setListeAgences'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'titre' => 'getTitre',
'nom' => 'getNom',
'prenom' => 'getPrenom',
'id_ref' => 'getIdRef',
'nom_jf' => 'getNomJf',
'qualification' => 'getQualification',
'nationalite' => 'getNationalite',
'date_naissance' => 'getDateNaissance',
'telephone_portable' => 'getTelephonePortable',
'telephone_domicile' => 'getTelephoneDomicile',
'qualif' => 'getQualif',
'bq_iban' => 'getBqIban',
'bq_bic' => 'getBqBic',
'bq_titulaire' => 'getBqTitulaire',
'bq_domiciliation' => 'getBqDomiciliation',
'email' => 'getEmail',
'nom_voie' => 'getNomVoie',
'num_voie' => 'getNumVoie',
'comp_voie' => 'getCompVoie',
'bis_voie' => 'getBisVoie',
'cp' => 'getCp',
'insee_commune' => 'getInseeCommune',
'commune' => 'getCommune',
'num_secu' => 'getNumSecu',
'num_secu_cle' => 'getNumSecuCle',
'lieu_naiss' => 'getLieuNaiss',
'pays_naiss' => 'getPaysNaiss',
'pays' => 'getPays',
'liste_agences' => 'getListeAgences'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['titre'] = isset($data['titre']) ? $data['titre'] : null;
        $this->container['nom'] = isset($data['nom']) ? $data['nom'] : null;
        $this->container['prenom'] = isset($data['prenom']) ? $data['prenom'] : null;
        $this->container['id_ref'] = isset($data['id_ref']) ? $data['id_ref'] : null;
        $this->container['nom_jf'] = isset($data['nom_jf']) ? $data['nom_jf'] : null;
        $this->container['qualification'] = isset($data['qualification']) ? $data['qualification'] : null;
        $this->container['nationalite'] = isset($data['nationalite']) ? $data['nationalite'] : null;
        $this->container['date_naissance'] = isset($data['date_naissance']) ? $data['date_naissance'] : null;
        $this->container['telephone_portable'] = isset($data['telephone_portable']) ? $data['telephone_portable'] : null;
        $this->container['telephone_domicile'] = isset($data['telephone_domicile']) ? $data['telephone_domicile'] : null;
        $this->container['qualif'] = isset($data['qualif']) ? $data['qualif'] : null;
        $this->container['bq_iban'] = isset($data['bq_iban']) ? $data['bq_iban'] : null;
        $this->container['bq_bic'] = isset($data['bq_bic']) ? $data['bq_bic'] : null;
        $this->container['bq_titulaire'] = isset($data['bq_titulaire']) ? $data['bq_titulaire'] : null;
        $this->container['bq_domiciliation'] = isset($data['bq_domiciliation']) ? $data['bq_domiciliation'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['nom_voie'] = isset($data['nom_voie']) ? $data['nom_voie'] : null;
        $this->container['num_voie'] = isset($data['num_voie']) ? $data['num_voie'] : null;
        $this->container['comp_voie'] = isset($data['comp_voie']) ? $data['comp_voie'] : null;
        $this->container['bis_voie'] = isset($data['bis_voie']) ? $data['bis_voie'] : null;
        $this->container['cp'] = isset($data['cp']) ? $data['cp'] : null;
        $this->container['insee_commune'] = isset($data['insee_commune']) ? $data['insee_commune'] : null;
        $this->container['commune'] = isset($data['commune']) ? $data['commune'] : null;
        $this->container['num_secu'] = isset($data['num_secu']) ? $data['num_secu'] : null;
        $this->container['num_secu_cle'] = isset($data['num_secu_cle']) ? $data['num_secu_cle'] : null;
        $this->container['lieu_naiss'] = isset($data['lieu_naiss']) ? $data['lieu_naiss'] : null;
        $this->container['pays_naiss'] = isset($data['pays_naiss']) ? $data['pays_naiss'] : null;
        $this->container['pays'] = isset($data['pays']) ? $data['pays'] : null;
        $this->container['liste_agences'] = isset($data['liste_agences']) ? $data['liste_agences'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets titre
     *
     * @return int
     */
    public function getTitre()
    {
        return $this->container['titre'];
    }

    /**
     * Sets titre
     *
     * @param int $titre titre
     *
     * @return $this
     */
    public function setTitre($titre)
    {
        $this->container['titre'] = $titre;

        return $this;
    }

    /**
     * Gets nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->container['nom'];
    }

    /**
     * Sets nom
     *
     * @param string $nom nom
     *
     * @return $this
     */
    public function setNom($nom)
    {
        $this->container['nom'] = $nom;

        return $this;
    }

    /**
     * Gets prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->container['prenom'];
    }

    /**
     * Sets prenom
     *
     * @param string $prenom prenom
     *
     * @return $this
     */
    public function setPrenom($prenom)
    {
        $this->container['prenom'] = $prenom;

        return $this;
    }

    /**
     * Gets id_ref
     *
     * @return string
     */
    public function getIdRef()
    {
        return $this->container['id_ref'];
    }

    /**
     * Sets id_ref
     *
     * @param string $id_ref id_ref
     *
     * @return $this
     */
    public function setIdRef($id_ref)
    {
        $this->container['id_ref'] = $id_ref;

        return $this;
    }

    /**
     * Gets nom_jf
     *
     * @return string
     */
    public function getNomJf()
    {
        return $this->container['nom_jf'];
    }

    /**
     * Sets nom_jf
     *
     * @param string $nom_jf nom_jf
     *
     * @return $this
     */
    public function setNomJf($nom_jf)
    {
        $this->container['nom_jf'] = $nom_jf;

        return $this;
    }

    /**
     * Gets qualification
     *
     * @return string
     */
    public function getQualification()
    {
        return $this->container['qualification'];
    }

    /**
     * Sets qualification
     *
     * @param string $qualification qualification
     *
     * @return $this
     */
    public function setQualification($qualification)
    {
        $this->container['qualification'] = $qualification;

        return $this;
    }

    /**
     * Gets nationalite
     *
     * @return string
     */
    public function getNationalite()
    {
        return $this->container['nationalite'];
    }

    /**
     * Sets nationalite
     *
     * @param string $nationalite nationalite
     *
     * @return $this
     */
    public function setNationalite($nationalite)
    {
        $this->container['nationalite'] = $nationalite;

        return $this;
    }

    /**
     * Gets date_naissance
     *
     * @return \DateTime
     */
    public function getDateNaissance()
    {
        return $this->container['date_naissance'];
    }

    /**
     * Sets date_naissance
     *
     * @param \DateTime $date_naissance date_naissance
     *
     * @return $this
     */
    public function setDateNaissance($date_naissance)
    {
        $this->container['date_naissance'] = $date_naissance;

        return $this;
    }

    /**
     * Gets telephone_portable
     *
     * @return string
     */
    public function getTelephonePortable()
    {
        return $this->container['telephone_portable'];
    }

    /**
     * Sets telephone_portable
     *
     * @param string $telephone_portable telephone_portable
     *
     * @return $this
     */
    public function setTelephonePortable($telephone_portable)
    {
        $this->container['telephone_portable'] = $telephone_portable;

        return $this;
    }

    /**
     * Gets telephone_domicile
     *
     * @return string
     */
    public function getTelephoneDomicile()
    {
        return $this->container['telephone_domicile'];
    }

    /**
     * Sets telephone_domicile
     *
     * @param string $telephone_domicile telephone_domicile
     *
     * @return $this
     */
    public function setTelephoneDomicile($telephone_domicile)
    {
        $this->container['telephone_domicile'] = $telephone_domicile;

        return $this;
    }

    /**
     * Gets qualif
     *
     * @return string
     */
    public function getQualif()
    {
        return $this->container['qualif'];
    }

    /**
     * Sets qualif
     *
     * @param string $qualif qualif
     *
     * @return $this
     */
    public function setQualif($qualif)
    {
        $this->container['qualif'] = $qualif;

        return $this;
    }

    /**
     * Gets bq_iban
     *
     * @return string
     */
    public function getBqIban()
    {
        return $this->container['bq_iban'];
    }

    /**
     * Sets bq_iban
     *
     * @param string $bq_iban bq_iban
     *
     * @return $this
     */
    public function setBqIban($bq_iban)
    {
        $this->container['bq_iban'] = $bq_iban;

        return $this;
    }

    /**
     * Gets bq_bic
     *
     * @return string
     */
    public function getBqBic()
    {
        return $this->container['bq_bic'];
    }

    /**
     * Sets bq_bic
     *
     * @param string $bq_bic bq_bic
     *
     * @return $this
     */
    public function setBqBic($bq_bic)
    {
        $this->container['bq_bic'] = $bq_bic;

        return $this;
    }

    /**
     * Gets bq_titulaire
     *
     * @return string
     */
    public function getBqTitulaire()
    {
        return $this->container['bq_titulaire'];
    }

    /**
     * Sets bq_titulaire
     *
     * @param string $bq_titulaire bq_titulaire
     *
     * @return $this
     */
    public function setBqTitulaire($bq_titulaire)
    {
        $this->container['bq_titulaire'] = $bq_titulaire;

        return $this;
    }

    /**
     * Gets bq_domiciliation
     *
     * @return string
     */
    public function getBqDomiciliation()
    {
        return $this->container['bq_domiciliation'];
    }

    /**
     * Sets bq_domiciliation
     *
     * @param string $bq_domiciliation bq_domiciliation
     *
     * @return $this
     */
    public function setBqDomiciliation($bq_domiciliation)
    {
        $this->container['bq_domiciliation'] = $bq_domiciliation;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets nom_voie
     *
     * @return string
     */
    public function getNomVoie()
    {
        return $this->container['nom_voie'];
    }

    /**
     * Sets nom_voie
     *
     * @param string $nom_voie nom_voie
     *
     * @return $this
     */
    public function setNomVoie($nom_voie)
    {
        $this->container['nom_voie'] = $nom_voie;

        return $this;
    }

    /**
     * Gets num_voie
     *
     * @return string
     */
    public function getNumVoie()
    {
        return $this->container['num_voie'];
    }

    /**
     * Sets num_voie
     *
     * @param string $num_voie num_voie
     *
     * @return $this
     */
    public function setNumVoie($num_voie)
    {
        $this->container['num_voie'] = $num_voie;

        return $this;
    }

    /**
     * Gets comp_voie
     *
     * @return string
     */
    public function getCompVoie()
    {
        return $this->container['comp_voie'];
    }

    /**
     * Sets comp_voie
     *
     * @param string $comp_voie comp_voie
     *
     * @return $this
     */
    public function setCompVoie($comp_voie)
    {
        $this->container['comp_voie'] = $comp_voie;

        return $this;
    }

    /**
     * Gets bis_voie
     *
     * @return string
     */
    public function getBisVoie()
    {
        return $this->container['bis_voie'];
    }

    /**
     * Sets bis_voie
     *
     * @param string $bis_voie bis_voie
     *
     * @return $this
     */
    public function setBisVoie($bis_voie)
    {
        $this->container['bis_voie'] = $bis_voie;

        return $this;
    }

    /**
     * Gets cp
     *
     * @return string
     */
    public function getCp()
    {
        return $this->container['cp'];
    }

    /**
     * Sets cp
     *
     * @param string $cp cp
     *
     * @return $this
     */
    public function setCp($cp)
    {
        $this->container['cp'] = $cp;

        return $this;
    }

    /**
     * Gets insee_commune
     *
     * @return string
     */
    public function getInseeCommune()
    {
        return $this->container['insee_commune'];
    }

    /**
     * Sets insee_commune
     *
     * @param string $insee_commune insee_commune
     *
     * @return $this
     */
    public function setInseeCommune($insee_commune)
    {
        $this->container['insee_commune'] = $insee_commune;

        return $this;
    }

    /**
     * Gets commune
     *
     * @return string
     */
    public function getCommune()
    {
        return $this->container['commune'];
    }

    /**
     * Sets commune
     *
     * @param string $commune commune
     *
     * @return $this
     */
    public function setCommune($commune)
    {
        $this->container['commune'] = $commune;

        return $this;
    }

    /**
     * Gets num_secu
     *
     * @return string
     */
    public function getNumSecu()
    {
        return $this->container['num_secu'];
    }

    /**
     * Sets num_secu
     *
     * @param string $num_secu num_secu
     *
     * @return $this
     */
    public function setNumSecu($num_secu)
    {
        $this->container['num_secu'] = $num_secu;

        return $this;
    }

    /**
     * Gets num_secu_cle
     *
     * @return string
     */
    public function getNumSecuCle()
    {
        return $this->container['num_secu_cle'];
    }

    /**
     * Sets num_secu_cle
     *
     * @param string $num_secu_cle num_secu_cle
     *
     * @return $this
     */
    public function setNumSecuCle($num_secu_cle)
    {
        $this->container['num_secu_cle'] = $num_secu_cle;

        return $this;
    }

    /**
     * Gets lieu_naiss
     *
     * @return string
     */
    public function getLieuNaiss()
    {
        return $this->container['lieu_naiss'];
    }

    /**
     * Sets lieu_naiss
     *
     * @param string $lieu_naiss lieu_naiss
     *
     * @return $this
     */
    public function setLieuNaiss($lieu_naiss)
    {
        $this->container['lieu_naiss'] = $lieu_naiss;

        return $this;
    }

    /**
     * Gets pays_naiss
     *
     * @return string
     */
    public function getPaysNaiss()
    {
        return $this->container['pays_naiss'];
    }

    /**
     * Sets pays_naiss
     *
     * @param string $pays_naiss pays_naiss
     *
     * @return $this
     */
    public function setPaysNaiss($pays_naiss)
    {
        $this->container['pays_naiss'] = $pays_naiss;

        return $this;
    }

    /**
     * Gets pays
     *
     * @return string
     */
    public function getPays()
    {
        return $this->container['pays'];
    }

    /**
     * Sets pays
     *
     * @param string $pays pays
     *
     * @return $this
     */
    public function setPays($pays)
    {
        $this->container['pays'] = $pays;

        return $this;
    }

    /**
     * Gets liste_agences
     *
     * @return string[]
     */
    public function getListeAgences()
    {
        return $this->container['liste_agences'];
    }

    /**
     * Sets liste_agences
     *
     * @param string[] $liste_agences liste_agences
     *
     * @return $this
     */
    public function setListeAgences($liste_agences)
    {
        $this->container['liste_agences'] = $liste_agences;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
