<?php
/**
 * ClientRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EvoliaApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace EvoliaV3\Model;

use \ArrayAccess;
use \EvoliaV3\ObjectSerializer;

/**
 * ClientRequest Class Doc Comment
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClientRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ClientRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id_ref' => 'int',
'name' => 'string',
'name_short' => 'string',
'customer_order' => 'int',
'designation' => 'string',
'address1' => 'string',
'address2' => 'string',
'address3' => 'string',
'postalcode' => 'string',
'city' => 'string',
'country' => 'string',
'phone' => 'string',
'fax' => 'string',
'email' => 'string',
'user' => 'string',
'web' => 'string',
'insee_commune' => 'string',
'ape' => 'string',
'tva_pays' => 'string',
'tva_cle' => 'string',
'siren' => 'string',
'nic' => 'string',
'id_agency' => 'string',
'bill_name' => 'string',
'bill_address1' => 'string',
'bill_address2' => 'string',
'bill_address3' => 'string',
'bill_postalcode' => 'string',
'bill_city' => 'string',
'bill_country' => 'string',
'bill_siren' => 'string',
'bill_nic' => 'string',
'bill_phone' => 'string',
'bill_fax' => 'string',
'bill_email' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id_ref' => 'int32',
'name' => null,
'name_short' => null,
'customer_order' => 'int32',
'designation' => null,
'address1' => null,
'address2' => null,
'address3' => null,
'postalcode' => null,
'city' => null,
'country' => null,
'phone' => 'tel',
'fax' => 'tel',
'email' => 'email',
'user' => null,
'web' => null,
'insee_commune' => null,
'ape' => null,
'tva_pays' => null,
'tva_cle' => null,
'siren' => null,
'nic' => null,
'id_agency' => null,
'bill_name' => null,
'bill_address1' => null,
'bill_address2' => null,
'bill_address3' => null,
'bill_postalcode' => null,
'bill_city' => null,
'bill_country' => null,
'bill_siren' => null,
'bill_nic' => null,
'bill_phone' => null,
'bill_fax' => null,
'bill_email' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_ref' => 'idRef',
'name' => 'name',
'name_short' => 'nameShort',
'customer_order' => 'customerOrder',
'designation' => 'designation',
'address1' => 'address1',
'address2' => 'address2',
'address3' => 'address3',
'postalcode' => 'postalcode',
'city' => 'city',
'country' => 'country',
'phone' => 'phone',
'fax' => 'fax',
'email' => 'email',
'user' => 'user',
'web' => 'web',
'insee_commune' => 'inseeCommune',
'ape' => 'ape',
'tva_pays' => 'tvaPays',
'tva_cle' => 'tvaCle',
'siren' => 'siren',
'nic' => 'nic',
'id_agency' => 'idAgency',
'bill_name' => 'billName',
'bill_address1' => 'billAddress1',
'bill_address2' => 'billAddress2',
'bill_address3' => 'billAddress3',
'bill_postalcode' => 'billPostalcode',
'bill_city' => 'billCity',
'bill_country' => 'billCountry',
'bill_siren' => 'billSiren',
'bill_nic' => 'billNic',
'bill_phone' => 'billPhone',
'bill_fax' => 'billFax',
'bill_email' => 'billEmail'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_ref' => 'setIdRef',
'name' => 'setName',
'name_short' => 'setNameShort',
'customer_order' => 'setCustomerOrder',
'designation' => 'setDesignation',
'address1' => 'setAddress1',
'address2' => 'setAddress2',
'address3' => 'setAddress3',
'postalcode' => 'setPostalcode',
'city' => 'setCity',
'country' => 'setCountry',
'phone' => 'setPhone',
'fax' => 'setFax',
'email' => 'setEmail',
'user' => 'setUser',
'web' => 'setWeb',
'insee_commune' => 'setInseeCommune',
'ape' => 'setApe',
'tva_pays' => 'setTvaPays',
'tva_cle' => 'setTvaCle',
'siren' => 'setSiren',
'nic' => 'setNic',
'id_agency' => 'setIdAgency',
'bill_name' => 'setBillName',
'bill_address1' => 'setBillAddress1',
'bill_address2' => 'setBillAddress2',
'bill_address3' => 'setBillAddress3',
'bill_postalcode' => 'setBillPostalcode',
'bill_city' => 'setBillCity',
'bill_country' => 'setBillCountry',
'bill_siren' => 'setBillSiren',
'bill_nic' => 'setBillNic',
'bill_phone' => 'setBillPhone',
'bill_fax' => 'setBillFax',
'bill_email' => 'setBillEmail'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_ref' => 'getIdRef',
'name' => 'getName',
'name_short' => 'getNameShort',
'customer_order' => 'getCustomerOrder',
'designation' => 'getDesignation',
'address1' => 'getAddress1',
'address2' => 'getAddress2',
'address3' => 'getAddress3',
'postalcode' => 'getPostalcode',
'city' => 'getCity',
'country' => 'getCountry',
'phone' => 'getPhone',
'fax' => 'getFax',
'email' => 'getEmail',
'user' => 'getUser',
'web' => 'getWeb',
'insee_commune' => 'getInseeCommune',
'ape' => 'getApe',
'tva_pays' => 'getTvaPays',
'tva_cle' => 'getTvaCle',
'siren' => 'getSiren',
'nic' => 'getNic',
'id_agency' => 'getIdAgency',
'bill_name' => 'getBillName',
'bill_address1' => 'getBillAddress1',
'bill_address2' => 'getBillAddress2',
'bill_address3' => 'getBillAddress3',
'bill_postalcode' => 'getBillPostalcode',
'bill_city' => 'getBillCity',
'bill_country' => 'getBillCountry',
'bill_siren' => 'getBillSiren',
'bill_nic' => 'getBillNic',
'bill_phone' => 'getBillPhone',
'bill_fax' => 'getBillFax',
'bill_email' => 'getBillEmail'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_ref'] = isset($data['id_ref']) ? $data['id_ref'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['name_short'] = isset($data['name_short']) ? $data['name_short'] : null;
        $this->container['customer_order'] = isset($data['customer_order']) ? $data['customer_order'] : null;
        $this->container['designation'] = isset($data['designation']) ? $data['designation'] : null;
        $this->container['address1'] = isset($data['address1']) ? $data['address1'] : null;
        $this->container['address2'] = isset($data['address2']) ? $data['address2'] : null;
        $this->container['address3'] = isset($data['address3']) ? $data['address3'] : null;
        $this->container['postalcode'] = isset($data['postalcode']) ? $data['postalcode'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
        $this->container['fax'] = isset($data['fax']) ? $data['fax'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['user'] = isset($data['user']) ? $data['user'] : null;
        $this->container['web'] = isset($data['web']) ? $data['web'] : null;
        $this->container['insee_commune'] = isset($data['insee_commune']) ? $data['insee_commune'] : null;
        $this->container['ape'] = isset($data['ape']) ? $data['ape'] : null;
        $this->container['tva_pays'] = isset($data['tva_pays']) ? $data['tva_pays'] : null;
        $this->container['tva_cle'] = isset($data['tva_cle']) ? $data['tva_cle'] : null;
        $this->container['siren'] = isset($data['siren']) ? $data['siren'] : null;
        $this->container['nic'] = isset($data['nic']) ? $data['nic'] : null;
        $this->container['id_agency'] = isset($data['id_agency']) ? $data['id_agency'] : null;
        $this->container['bill_name'] = isset($data['bill_name']) ? $data['bill_name'] : null;
        $this->container['bill_address1'] = isset($data['bill_address1']) ? $data['bill_address1'] : null;
        $this->container['bill_address2'] = isset($data['bill_address2']) ? $data['bill_address2'] : null;
        $this->container['bill_address3'] = isset($data['bill_address3']) ? $data['bill_address3'] : null;
        $this->container['bill_postalcode'] = isset($data['bill_postalcode']) ? $data['bill_postalcode'] : null;
        $this->container['bill_city'] = isset($data['bill_city']) ? $data['bill_city'] : null;
        $this->container['bill_country'] = isset($data['bill_country']) ? $data['bill_country'] : null;
        $this->container['bill_siren'] = isset($data['bill_siren']) ? $data['bill_siren'] : null;
        $this->container['bill_nic'] = isset($data['bill_nic']) ? $data['bill_nic'] : null;
        $this->container['bill_phone'] = isset($data['bill_phone']) ? $data['bill_phone'] : null;
        $this->container['bill_fax'] = isset($data['bill_fax']) ? $data['bill_fax'] : null;
        $this->container['bill_email'] = isset($data['bill_email']) ? $data['bill_email'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['ape'] === null) {
            $invalidProperties[] = "'ape' can't be null";
        }
        if ($this->container['id_agency'] === null) {
            $invalidProperties[] = "'id_agency' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_ref
     *
     * @return int
     */
    public function getIdRef()
    {
        return $this->container['id_ref'];
    }

    /**
     * Sets id_ref
     *
     * @param int $id_ref id_ref
     *
     * @return $this
     */
    public function setIdRef($id_ref)
    {
        $this->container['id_ref'] = $id_ref;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets name_short
     *
     * @return string
     */
    public function getNameShort()
    {
        return $this->container['name_short'];
    }

    /**
     * Sets name_short
     *
     * @param string $name_short name_short
     *
     * @return $this
     */
    public function setNameShort($name_short)
    {
        $this->container['name_short'] = $name_short;

        return $this;
    }

    /**
     * Gets customer_order
     *
     * @return int
     */
    public function getCustomerOrder()
    {
        return $this->container['customer_order'];
    }

    /**
     * Sets customer_order
     *
     * @param int $customer_order customer_order
     *
     * @return $this
     */
    public function setCustomerOrder($customer_order)
    {
        $this->container['customer_order'] = $customer_order;

        return $this;
    }

    /**
     * Gets designation
     *
     * @return string
     */
    public function getDesignation()
    {
        return $this->container['designation'];
    }

    /**
     * Sets designation
     *
     * @param string $designation designation
     *
     * @return $this
     */
    public function setDesignation($designation)
    {
        $this->container['designation'] = $designation;

        return $this;
    }

    /**
     * Gets address1
     *
     * @return string
     */
    public function getAddress1()
    {
        return $this->container['address1'];
    }

    /**
     * Sets address1
     *
     * @param string $address1 address1
     *
     * @return $this
     */
    public function setAddress1($address1)
    {
        $this->container['address1'] = $address1;

        return $this;
    }

    /**
     * Gets address2
     *
     * @return string
     */
    public function getAddress2()
    {
        return $this->container['address2'];
    }

    /**
     * Sets address2
     *
     * @param string $address2 address2
     *
     * @return $this
     */
    public function setAddress2($address2)
    {
        $this->container['address2'] = $address2;

        return $this;
    }

    /**
     * Gets address3
     *
     * @return string
     */
    public function getAddress3()
    {
        return $this->container['address3'];
    }

    /**
     * Sets address3
     *
     * @param string $address3 address3
     *
     * @return $this
     */
    public function setAddress3($address3)
    {
        $this->container['address3'] = $address3;

        return $this;
    }

    /**
     * Gets postalcode
     *
     * @return string
     */
    public function getPostalcode()
    {
        return $this->container['postalcode'];
    }

    /**
     * Sets postalcode
     *
     * @param string $postalcode postalcode
     *
     * @return $this
     */
    public function setPostalcode($postalcode)
    {
        $this->container['postalcode'] = $postalcode;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city city
     *
     * @return $this
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone phone
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets fax
     *
     * @return string
     */
    public function getFax()
    {
        return $this->container['fax'];
    }

    /**
     * Sets fax
     *
     * @param string $fax fax
     *
     * @return $this
     */
    public function setFax($fax)
    {
        $this->container['fax'] = $fax;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets user
     *
     * @return string
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param string $user user
     *
     * @return $this
     */
    public function setUser($user)
    {
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets web
     *
     * @return string
     */
    public function getWeb()
    {
        return $this->container['web'];
    }

    /**
     * Sets web
     *
     * @param string $web web
     *
     * @return $this
     */
    public function setWeb($web)
    {
        $this->container['web'] = $web;

        return $this;
    }

    /**
     * Gets insee_commune
     *
     * @return string
     */
    public function getInseeCommune()
    {
        return $this->container['insee_commune'];
    }

    /**
     * Sets insee_commune
     *
     * @param string $insee_commune insee_commune
     *
     * @return $this
     */
    public function setInseeCommune($insee_commune)
    {
        $this->container['insee_commune'] = $insee_commune;

        return $this;
    }

    /**
     * Gets ape
     *
     * @return string
     */
    public function getApe()
    {
        return $this->container['ape'];
    }

    /**
     * Sets ape
     *
     * @param string $ape ape
     *
     * @return $this
     */
    public function setApe($ape)
    {
        $this->container['ape'] = $ape;

        return $this;
    }

    /**
     * Gets tva_pays
     *
     * @return string
     */
    public function getTvaPays()
    {
        return $this->container['tva_pays'];
    }

    /**
     * Sets tva_pays
     *
     * @param string $tva_pays tva_pays
     *
     * @return $this
     */
    public function setTvaPays($tva_pays)
    {
        $this->container['tva_pays'] = $tva_pays;

        return $this;
    }

    /**
     * Gets tva_cle
     *
     * @return string
     */
    public function getTvaCle()
    {
        return $this->container['tva_cle'];
    }

    /**
     * Sets tva_cle
     *
     * @param string $tva_cle tva_cle
     *
     * @return $this
     */
    public function setTvaCle($tva_cle)
    {
        $this->container['tva_cle'] = $tva_cle;

        return $this;
    }

    /**
     * Gets siren
     *
     * @return string
     */
    public function getSiren()
    {
        return $this->container['siren'];
    }

    /**
     * Sets siren
     *
     * @param string $siren siren
     *
     * @return $this
     */
    public function setSiren($siren)
    {
        $this->container['siren'] = $siren;

        return $this;
    }

    /**
     * Gets nic
     *
     * @return string
     */
    public function getNic()
    {
        return $this->container['nic'];
    }

    /**
     * Sets nic
     *
     * @param string $nic nic
     *
     * @return $this
     */
    public function setNic($nic)
    {
        $this->container['nic'] = $nic;

        return $this;
    }

    /**
     * Gets id_agency
     *
     * @return string
     */
    public function getIdAgency()
    {
        return $this->container['id_agency'];
    }

    /**
     * Sets id_agency
     *
     * @param string $id_agency id_agency
     *
     * @return $this
     */
    public function setIdAgency($id_agency)
    {
        $this->container['id_agency'] = $id_agency;

        return $this;
    }

    /**
     * Gets bill_name
     *
     * @return string
     */
    public function getBillName()
    {
        return $this->container['bill_name'];
    }

    /**
     * Sets bill_name
     *
     * @param string $bill_name bill_name
     *
     * @return $this
     */
    public function setBillName($bill_name)
    {
        $this->container['bill_name'] = $bill_name;

        return $this;
    }

    /**
     * Gets bill_address1
     *
     * @return string
     */
    public function getBillAddress1()
    {
        return $this->container['bill_address1'];
    }

    /**
     * Sets bill_address1
     *
     * @param string $bill_address1 bill_address1
     *
     * @return $this
     */
    public function setBillAddress1($bill_address1)
    {
        $this->container['bill_address1'] = $bill_address1;

        return $this;
    }

    /**
     * Gets bill_address2
     *
     * @return string
     */
    public function getBillAddress2()
    {
        return $this->container['bill_address2'];
    }

    /**
     * Sets bill_address2
     *
     * @param string $bill_address2 bill_address2
     *
     * @return $this
     */
    public function setBillAddress2($bill_address2)
    {
        $this->container['bill_address2'] = $bill_address2;

        return $this;
    }

    /**
     * Gets bill_address3
     *
     * @return string
     */
    public function getBillAddress3()
    {
        return $this->container['bill_address3'];
    }

    /**
     * Sets bill_address3
     *
     * @param string $bill_address3 bill_address3
     *
     * @return $this
     */
    public function setBillAddress3($bill_address3)
    {
        $this->container['bill_address3'] = $bill_address3;

        return $this;
    }

    /**
     * Gets bill_postalcode
     *
     * @return string
     */
    public function getBillPostalcode()
    {
        return $this->container['bill_postalcode'];
    }

    /**
     * Sets bill_postalcode
     *
     * @param string $bill_postalcode bill_postalcode
     *
     * @return $this
     */
    public function setBillPostalcode($bill_postalcode)
    {
        $this->container['bill_postalcode'] = $bill_postalcode;

        return $this;
    }

    /**
     * Gets bill_city
     *
     * @return string
     */
    public function getBillCity()
    {
        return $this->container['bill_city'];
    }

    /**
     * Sets bill_city
     *
     * @param string $bill_city bill_city
     *
     * @return $this
     */
    public function setBillCity($bill_city)
    {
        $this->container['bill_city'] = $bill_city;

        return $this;
    }

    /**
     * Gets bill_country
     *
     * @return string
     */
    public function getBillCountry()
    {
        return $this->container['bill_country'];
    }

    /**
     * Sets bill_country
     *
     * @param string $bill_country bill_country
     *
     * @return $this
     */
    public function setBillCountry($bill_country)
    {
        $this->container['bill_country'] = $bill_country;

        return $this;
    }

    /**
     * Gets bill_siren
     *
     * @return string
     */
    public function getBillSiren()
    {
        return $this->container['bill_siren'];
    }

    /**
     * Sets bill_siren
     *
     * @param string $bill_siren bill_siren
     *
     * @return $this
     */
    public function setBillSiren($bill_siren)
    {
        $this->container['bill_siren'] = $bill_siren;

        return $this;
    }

    /**
     * Gets bill_nic
     *
     * @return string
     */
    public function getBillNic()
    {
        return $this->container['bill_nic'];
    }

    /**
     * Sets bill_nic
     *
     * @param string $bill_nic bill_nic
     *
     * @return $this
     */
    public function setBillNic($bill_nic)
    {
        $this->container['bill_nic'] = $bill_nic;

        return $this;
    }

    /**
     * Gets bill_phone
     *
     * @return string
     */
    public function getBillPhone()
    {
        return $this->container['bill_phone'];
    }

    /**
     * Sets bill_phone
     *
     * @param string $bill_phone bill_phone
     *
     * @return $this
     */
    public function setBillPhone($bill_phone)
    {
        $this->container['bill_phone'] = $bill_phone;

        return $this;
    }

    /**
     * Gets bill_fax
     *
     * @return string
     */
    public function getBillFax()
    {
        return $this->container['bill_fax'];
    }

    /**
     * Sets bill_fax
     *
     * @param string $bill_fax bill_fax
     *
     * @return $this
     */
    public function setBillFax($bill_fax)
    {
        $this->container['bill_fax'] = $bill_fax;

        return $this;
    }

    /**
     * Gets bill_email
     *
     * @return string
     */
    public function getBillEmail()
    {
        return $this->container['bill_email'];
    }

    /**
     * Sets bill_email
     *
     * @param string $bill_email bill_email
     *
     * @return $this
     */
    public function setBillEmail($bill_email)
    {
        $this->container['bill_email'] = $bill_email;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
