<?php
/**
 * WorkDays
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EvoliaApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace EvoliaV3\Model;

use \ArrayAccess;
use \EvoliaV3\ObjectSerializer;

/**
 * WorkDays Class Doc Comment
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WorkDays implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WorkDays';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'date' => '\DateTime',
'daytime' => 'double',
'nighttime' => 'double',
'is_absent' => 'bool',
'payroll_items' => '\EvoliaV3\Model\PayrollItemsPart[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'date' => 'date-time',
'daytime' => 'double',
'nighttime' => 'double',
'is_absent' => null,
'payroll_items' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date' => 'date',
'daytime' => 'daytime',
'nighttime' => 'nighttime',
'is_absent' => 'isAbsent',
'payroll_items' => 'payrollItems'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date' => 'setDate',
'daytime' => 'setDaytime',
'nighttime' => 'setNighttime',
'is_absent' => 'setIsAbsent',
'payroll_items' => 'setPayrollItems'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date' => 'getDate',
'daytime' => 'getDaytime',
'nighttime' => 'getNighttime',
'is_absent' => 'getIsAbsent',
'payroll_items' => 'getPayrollItems'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['date'] = isset($data['date']) ? $data['date'] : null;
        $this->container['daytime'] = isset($data['daytime']) ? $data['daytime'] : null;
        $this->container['nighttime'] = isset($data['nighttime']) ? $data['nighttime'] : null;
        $this->container['is_absent'] = isset($data['is_absent']) ? $data['is_absent'] : null;
        $this->container['payroll_items'] = isset($data['payroll_items']) ? $data['payroll_items'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['date'] === null) {
            $invalidProperties[] = "'date' can't be null";
        }
        if ($this->container['daytime'] === null) {
            $invalidProperties[] = "'daytime' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime $date date
     *
     * @return $this
     */
    public function setDate($date)
    {
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets daytime
     *
     * @return double
     */
    public function getDaytime()
    {
        return $this->container['daytime'];
    }

    /**
     * Sets daytime
     *
     * @param double $daytime daytime
     *
     * @return $this
     */
    public function setDaytime($daytime)
    {
        $this->container['daytime'] = $daytime;

        return $this;
    }

    /**
     * Gets nighttime
     *
     * @return double
     */
    public function getNighttime()
    {
        return $this->container['nighttime'];
    }

    /**
     * Sets nighttime
     *
     * @param double $nighttime nighttime
     *
     * @return $this
     */
    public function setNighttime($nighttime)
    {
        $this->container['nighttime'] = $nighttime;

        return $this;
    }

    /**
     * Gets is_absent
     *
     * @return bool
     */
    public function getIsAbsent()
    {
        return $this->container['is_absent'];
    }

    /**
     * Sets is_absent
     *
     * @param bool $is_absent is_absent
     *
     * @return $this
     */
    public function setIsAbsent($is_absent)
    {
        $this->container['is_absent'] = $is_absent;

        return $this;
    }

    /**
     * Gets payroll_items
     *
     * @return \EvoliaV3\Model\PayrollItemsPart[]
     */
    public function getPayrollItems()
    {
        return $this->container['payroll_items'];
    }

    /**
     * Sets payroll_items
     *
     * @param \EvoliaV3\Model\PayrollItemsPart[] $payroll_items payroll_items
     *
     * @return $this
     */
    public function setPayrollItems($payroll_items)
    {
        $this->container['payroll_items'] = $payroll_items;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
