<?php
/**
 * CandidateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EvoliaApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EvoliaV3;

/**
 * CandidateTest Class Doc Comment
 *
 * @category    Class
 * @description Candidate
 * @package     EvoliaV3
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CandidateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Candidate"
     */
    public function testCandidate()
    {
    }

    /**
     * Test attribute "titre"
     */
    public function testPropertyTitre()
    {
    }

    /**
     * Test attribute "nom"
     */
    public function testPropertyNom()
    {
    }

    /**
     * Test attribute "prenom"
     */
    public function testPropertyPrenom()
    {
    }

    /**
     * Test attribute "id_ref"
     */
    public function testPropertyIdRef()
    {
    }

    /**
     * Test attribute "nom_jf"
     */
    public function testPropertyNomJf()
    {
    }

    /**
     * Test attribute "qualification"
     */
    public function testPropertyQualification()
    {
    }

    /**
     * Test attribute "nationalite"
     */
    public function testPropertyNationalite()
    {
    }

    /**
     * Test attribute "date_naissance"
     */
    public function testPropertyDateNaissance()
    {
    }

    /**
     * Test attribute "telephone_portable"
     */
    public function testPropertyTelephonePortable()
    {
    }

    /**
     * Test attribute "telephone_domicile"
     */
    public function testPropertyTelephoneDomicile()
    {
    }

    /**
     * Test attribute "qualif"
     */
    public function testPropertyQualif()
    {
    }

    /**
     * Test attribute "bq_iban"
     */
    public function testPropertyBqIban()
    {
    }

    /**
     * Test attribute "bq_bic"
     */
    public function testPropertyBqBic()
    {
    }

    /**
     * Test attribute "bq_titulaire"
     */
    public function testPropertyBqTitulaire()
    {
    }

    /**
     * Test attribute "bq_domiciliation"
     */
    public function testPropertyBqDomiciliation()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "nom_voie"
     */
    public function testPropertyNomVoie()
    {
    }

    /**
     * Test attribute "num_voie"
     */
    public function testPropertyNumVoie()
    {
    }

    /**
     * Test attribute "comp_voie"
     */
    public function testPropertyCompVoie()
    {
    }

    /**
     * Test attribute "bis_voie"
     */
    public function testPropertyBisVoie()
    {
    }

    /**
     * Test attribute "cp"
     */
    public function testPropertyCp()
    {
    }

    /**
     * Test attribute "insee_commune"
     */
    public function testPropertyInseeCommune()
    {
    }

    /**
     * Test attribute "commune"
     */
    public function testPropertyCommune()
    {
    }

    /**
     * Test attribute "num_secu"
     */
    public function testPropertyNumSecu()
    {
    }

    /**
     * Test attribute "num_secu_cle"
     */
    public function testPropertyNumSecuCle()
    {
    }

    /**
     * Test attribute "lieu_naiss"
     */
    public function testPropertyLieuNaiss()
    {
    }

    /**
     * Test attribute "pays_naiss"
     */
    public function testPropertyPaysNaiss()
    {
    }

    /**
     * Test attribute "dep_naiss"
     */
    public function testPropertyDepNaiss()
    {
    }

    /**
     * Test attribute "n_comm_naiss"
     */
    public function testPropertyNCommNaiss()
    {
    }

    /**
     * Test attribute "pays"
     */
    public function testPropertyPays()
    {
    }

    /**
     * Test attribute "liste_agences"
     */
    public function testPropertyListeAgences()
    {
    }
}
