<?php
/**
 * ContractTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EvoliaApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EvoliaV3;

/**
 * ContractTest Class Doc Comment
 *
 * @category    Class
 * @description Contract
 * @package     EvoliaV3
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContractTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Contract"
     */
    public function testContract()
    {
    }

    /**
     * Test attribute "id_contract"
     */
    public function testPropertyIdContract()
    {
    }

    /**
     * Test attribute "id_personne"
     */
    public function testPropertyIdPersonne()
    {
    }

    /**
     * Test attribute "id_client"
     */
    public function testPropertyIdClient()
    {
    }

    /**
     * Test attribute "code_mission"
     */
    public function testPropertyCodeMission()
    {
    }

    /**
     * Test attribute "ordre_client"
     */
    public function testPropertyOrdreClient()
    {
    }

    /**
     * Test attribute "lieuxde_mission"
     */
    public function testPropertyLieuxdeMission()
    {
    }

    /**
     * Test attribute "adresse1"
     */
    public function testPropertyAdresse1()
    {
    }

    /**
     * Test attribute "cp"
     */
    public function testPropertyCp()
    {
    }

    /**
     * Test attribute "commune"
     */
    public function testPropertyCommune()
    {
    }

    /**
     * Test attribute "insee"
     */
    public function testPropertyInsee()
    {
    }

    /**
     * Test attribute "pays"
     */
    public function testPropertyPays()
    {
    }

    /**
     * Test attribute "agence"
     */
    public function testPropertyAgence()
    {
    }

    /**
     * Test attribute "debut"
     */
    public function testPropertyDebut()
    {
    }

    /**
     * Test attribute "fin_prevue"
     */
    public function testPropertyFinPrevue()
    {
    }

    /**
     * Test attribute "date_creation"
     */
    public function testPropertyDateCreation()
    {
    }

    /**
     * Test attribute "categorie_salariale"
     */
    public function testPropertyCategorieSalariale()
    {
    }

    /**
     * Test attribute "motif_embauche"
     */
    public function testPropertyMotifEmbauche()
    {
    }

    /**
     * Test attribute "justification"
     */
    public function testPropertyJustification()
    {
    }

    /**
     * Test attribute "mission_a_risque_l23131"
     */
    public function testPropertyMissionARisqueL23131()
    {
    }

    /**
     * Test attribute "heure_de_presentation"
     */
    public function testPropertyHeureDePresentation()
    {
    }

    /**
     * Test attribute "contract_order"
     */
    public function testPropertyContractOrder()
    {
    }

    /**
     * Test attribute "type_contrat"
     */
    public function testPropertyTypeContrat()
    {
    }

    /**
     * Test attribute "date_effet"
     */
    public function testPropertyDateEffet()
    {
    }

    /**
     * Test attribute "souplesse_debut"
     */
    public function testPropertySouplesseDebut()
    {
    }

    /**
     * Test attribute "souplesse_fin"
     */
    public function testPropertySouplesseFin()
    {
    }

    /**
     * Test attribute "taux_paye"
     */
    public function testPropertyTauxPaye()
    {
    }

    /**
     * Test attribute "taux_facture"
     */
    public function testPropertyTauxFacture()
    {
    }

    /**
     * Test attribute "lot_facture"
     */
    public function testPropertyLotFacture()
    {
    }

    /**
     * Test attribute "duree_hebdo"
     */
    public function testPropertyDureeHebdo()
    {
    }

    /**
     * Test attribute "metier"
     */
    public function testPropertyMetier()
    {
    }

    /**
     * Test attribute "seuil_et_decompte"
     */
    public function testPropertySeuilEtDecompte()
    {
    }

    /**
     * Test attribute "code_pcs"
     */
    public function testPropertyCodePcs()
    {
    }

    /**
     * Test attribute "reference_analytique"
     */
    public function testPropertyReferenceAnalytique()
    {
    }

    /**
     * Test attribute "retour_signature_interimaire"
     */
    public function testPropertyRetourSignatureInterimaire()
    {
    }

    /**
     * Test attribute "retour_signature_client"
     */
    public function testPropertyRetourSignatureClient()
    {
    }

    /**
     * Test attribute "rubriques_contratctuelles"
     */
    public function testPropertyRubriquesContratctuelles()
    {
    }
}
