<?php
/**
 * CustomerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EvoliaApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EvoliaV3;

/**
 * CustomerTest Class Doc Comment
 *
 * @category    Class
 * @description Customer
 * @package     EvoliaV3
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Customer"
     */
    public function testCustomer()
    {
    }

    /**
     * Test attribute "matricule"
     */
    public function testPropertyMatricule()
    {
    }

    /**
     * Test attribute "nom"
     */
    public function testPropertyNom()
    {
    }

    /**
     * Test attribute "nom_court"
     */
    public function testPropertyNomCourt()
    {
    }

    /**
     * Test attribute "ordre_client"
     */
    public function testPropertyOrdreClient()
    {
    }

    /**
     * Test attribute "designation"
     */
    public function testPropertyDesignation()
    {
    }

    /**
     * Test attribute "adresse1"
     */
    public function testPropertyAdresse1()
    {
    }

    /**
     * Test attribute "cp"
     */
    public function testPropertyCp()
    {
    }

    /**
     * Test attribute "commune"
     */
    public function testPropertyCommune()
    {
    }

    /**
     * Test attribute "pays"
     */
    public function testPropertyPays()
    {
    }

    /**
     * Test attribute "telephone"
     */
    public function testPropertyTelephone()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "ape"
     */
    public function testPropertyApe()
    {
    }

    /**
     * Test attribute "siren"
     */
    public function testPropertySiren()
    {
    }

    /**
     * Test attribute "nic"
     */
    public function testPropertyNic()
    {
    }

    /**
     * Test attribute "liste_agences"
     */
    public function testPropertyListeAgences()
    {
    }
}
