<?php
/**
 * CandidatesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EvoliaApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EvoliaV3;

use EvoliaV3\Configuration;
use EvoliaV3\ApiException;
use EvoliaV3\ObjectSerializer;

/**
 * CandidatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  EvoliaV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CandidatesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for importCandidate
     *
     * Import the Candidate.
     *
     */
    public function testImportCandidate()
    {
    }

    /**
     * Test case for searchCandidate
     *
     * Test if the Candidate exists.
     *
     */
    public function testSearchCandidate()
    {
    }

    /**
     * Test case for updateCandidate
     *
     * Update the Candidate.
     *
     */
    public function testUpdateCandidate()
    {
    }

    /**
     * Test case for updateDpaes
     *
     * Update the Candidate with DPAE information.
     *
     */
    public function testUpdateDpaes()
    {
    }
}
